# Generated by Django 4.1.7 on 2023-04-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
