# Generated by Django 4.1.7 on 2023-04-04 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_blog_picture'),
        ('blogapp', '0003_alter_blog_picture_like'),
    ]

    operations = [
    ]
