# Generated by Django 4.1.7 on 2023-04-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_merge_20230404_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Finance', 'Finance'), ('Tech', 'Tech'), ('Entertainment', 'Entertainment')], default='Entertainment', max_length=15, null=True),
        ),
    ]
