# Generated by Django 4.1.7 on 2023-04-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationapp', '0002_user_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='LikeAndDislike',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='commenting',
            field=models.TextField(null=True),
        ),
    ]
