# Generated by Django 4.1.7 on 2023-04-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationapp', '0003_user_likeanddislike_user_commenting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='LikeAndDislike',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
